# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  - 5.5
  #- 5.6
  #- 7.0
  #- hhvm

before_install:
  - composer self-update
  - composer --version

install:
  - composer install
  - composer install-npm

before_script:
  - cp app.TEMPLATE.yaml app.yaml

script:
  - composer test

notifications:
  #- iet-webmaster@open.ac.uk

#End.
